/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Cliente;
import Entidades.Usuario;
import EntidadesDAO.ClienteDAO;
import Paneles.frmVenta;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author andre
 */
public class frmClienteSeleccionar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCliente
     */
    ClienteDAO clienteDao;
    DefaultTableModel modelClientes;
    ArrayList<Cliente> listaClientes;
    Cliente clienteSeleccionado;
    String nombre, ubicacion;
    private Usuario userSesion;
    private Component rootPane;
    frmVenta parentVenta;

    public frmClienteSeleccionar(Usuario userFrmPrincipal) {
        initComponents();
        this.userSesion = userFrmPrincipal;
        this.clienteDao = new ClienteDAO();
        this.modelClientes = (DefaultTableModel) this.tblClientes.getModel();
        this.listaClientes = new ArrayList();
        configurarListenerBusqueda();
        this.listaClientes = this.clienteDao.ConsultarClientes();
        this.RecargarUsuarios();
        this.clienteSeleccionado = new Cliente();
    }

    public frmClienteSeleccionar(frmVenta parentFrm) {
        initComponents();
        this.parentVenta = parentFrm;
        this.clienteDao = new ClienteDAO();
        configurarListenerBusqueda();
        this.modelClientes = (DefaultTableModel) this.tblClientes.getModel();
        this.listaClientes = new ArrayList();
        this.listaClientes = this.clienteDao.ConsultarClientes();
        this.RecargarUsuarios();
        this.clienteSeleccionado = new Cliente();
    }

    private void RecargarUsuarios() {
        this.tblClientes.clearSelection();
        this.modelClientes.setRowCount(0);
        for (int i = 0; i < this.listaClientes.size(); i++) {
            Cliente cliente = this.listaClientes.get(i);
            String[] data = {cliente.getNombre(), cliente.getUbicacion()};
            this.modelClientes.addRow(data);
        }
    }

    private void configurarListenerBusqueda() {
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            // Método que actualiza el filtro al cambiar el texto
            private void actualizarFiltro() {
                // Obtener el texto de búsqueda
                String textoBusqueda = txtBuscar.getText(); // Asegúrate de que txtBuscar es el campo de texto donde el usuario ingresa el término de búsqueda

                // Llamar al método de filtrado
                filtrarTabla(textoBusqueda);
            }
        });
    }

    private void filtrarTabla(String textoBusqueda) {
        // Crear un RowFilter que busque coincidencias en las columnas de Nombre y Ubicación
        RowFilter<Object, Object> rf = RowFilter.regexFilter("(?i)" + textoBusqueda, 0, 1); // 0 y 1 son los índices de las columnas (Nombre y Ubicación)

        // Aplicar el filtro al modelo
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modelClientes);
        sorter.setRowFilter(rf);
        tblClientes.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cliente", "Ubicación"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 510, 540));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Categoria/lblFondoPequeño (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int filaSeleccionada = this.tblClientes.getSelectedRow();
        
        int filaOriginal = this.tblClientes.convertRowIndexToModel(filaSeleccionada);
        this.clienteSeleccionado = this.listaClientes.get(filaOriginal);
        this.parentVenta.ObtenerClienteSeleccionado(clienteSeleccionado);
        this.dispose();
    }//GEN-LAST:event_tblClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
