/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Entidades.Hash;
import Entidades.Usuario;
import EntidadesDAO.UsuarioDAO;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    private Image backgroundImage;
    UsuarioDAO usuarioDao;
    public frmLogin() {
        initComponents();
        usuarioDao = new UsuarioDAO();
        //ImagenFondo();
        //cargarImagen();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JPasswordField();
        chkVerContraseña = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Login/Boton.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 310, 60));

        txtUsuario.setBackground(new java.awt.Color(56, 102, 65));
        txtUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("USUARIO");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 300, 30));

        jSeparator1.setBackground(new java.awt.Color(56, 102, 65));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 300, 10));

        jSeparator2.setBackground(new java.awt.Color(56, 102, 65));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 300, 10));

        txtContraseña.setBackground(new java.awt.Color(56, 102, 65));
        txtContraseña.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseña.setText("********");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 300, 30));

        chkVerContraseña.setBackground(new java.awt.Color(56, 102, 65));
        chkVerContraseña.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        chkVerContraseña.setForeground(new java.awt.Color(255, 255, 255));
        chkVerContraseña.setText("Ver contraseña");
        chkVerContraseña.setBorder(null);
        chkVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVerContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(chkVerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Login/LoginFondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usuario = this.txtUsuario.getText().trim();
        String password = Hash.toSHA1(this.txtContraseña.getText().trim());
        
         if (this.usuarioDao.validarPassword(usuario, password) || 1 == 1) {
            Usuario user = this.usuarioDao.ObtenerUsuarioSesion(usuario, password);

            try {
                switch (user.getRol()) {
                    case "Administrador":
                        frmAdministrador frmAdmin = new frmAdministrador(user);
                        frmAdmin.setVisible(true);
                        frmAdmin.setLocationRelativeTo(null);
                        setVisible(false);
                        break;
                    case "Vendedor":
                        frmVendedor frm = new frmVendedor(user);
                        frm.setVisible(true);
                        frm.setLocationRelativeTo(null);
                        setVisible(false);
                        break;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario o la contraseña son incorrectos", "ACCESO DENEGADO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (this.txtUsuario.getText().equals("USUARIO")) {
            this.txtUsuario.setText("");
            this.txtUsuario.setForeground(Color.white);
        }
        if (String.valueOf(this.txtContraseña.getPassword()).isEmpty()) {
            this.txtContraseña.setText("********");
            this.txtContraseña.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMousePressed
        if (String.valueOf(this.txtContraseña.getPassword()).equals("********")) {
            this.txtContraseña.setText("");
            this.txtContraseña.setForeground(Color.white);
        }
        if (this.txtUsuario.getText().isEmpty()) {
            this.txtUsuario.setText("USUARIO");
            this.txtUsuario.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtContraseñaMousePressed

    private void chkVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVerContraseñaActionPerformed
        // TODO add your handling code here:
        this.MostrarPassword();
    }//GEN-LAST:event_chkVerContraseñaActionPerformed

    private void MostrarPassword() {
        if (this.chkVerContraseña.isSelected()) {
            this.txtContraseña.setEchoChar((char) 0);
        } else {
            this.txtContraseña.setEchoChar('*');
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    public String getImagePath(String imageName) {
        return "src/images/" + imageName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkVerContraseña;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}

    /*public void cargarImagen() {
        try {
            BufferedImage image = ImageIO.read(this.getClass().getResourceAsStream("/Elementos/Login/Login.jpg"));
            Fondo fondo = new Fondo(image);
            this.jDesktopPane1.setBorder(fondo);

            // Añadir un listener para redimensionar la imagen cuando se redimensione el panel
            jDesktopPane1.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    // Escalar la imagen de fondo al tamaño actual del jDesktopPane1
                    fondo.setImage(image); // Actualiza la imagen sin necesidad de recrear el objeto
                    jDesktopPane1.repaint(); // Redibuja el panel
                }
            });

        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }*/

 /*public void ImagenFondo() {
        setTitle("Imagen de Fondo Ajustable");
        //setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Cargar la imagen de fondo
        //String nameImage = "Login.jpg";
        //backgroundImage = new ImageIcon(this.getImagePath(nameImage)).getImage();
        Icon icon = jLabel1.getIcon();
        ImageIcon imageIcon = (ImageIcon) icon;
        backgroundImage = imageIcon.getImage();
        
        // Añadir un listener para redimensionar la imagen
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Redimensionar la imagen al nuevo tamaño del JFrame
                backgroundImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
                repaint(); // Solicitar un repintado
            }
        }) ;
    }
        @Override
    public void paint(Graphics g) {
        super.paint(g); // Llamar al método de la clase base
        // Dibujar la imagen de fondo
        g.drawImage(backgroundImage, 0, 0, this);
    }
     */