/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Paneles.frmLotes;
import EntidadesDAO.ProveedorDAO;
import Entidades.Proveedor;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kater
 */
public class frmVerProveedores extends javax.swing.JInternalFrame {

    private frmLotes parentForm;
    private ProveedorDAO provDAO;
    DefaultTableModel model;
    ArrayList<Proveedor> listaProveedores;
    
    /**
     * Creates new form frmVerProveedores
     */
    
    public frmVerProveedores() {
        initComponents();
        provDAO = new ProveedorDAO();
        this.model=(DefaultTableModel) this.jTable1.getModel();
        this.listaProveedores=new ArrayList();
        cargarTabla();
    }

    public frmVerProveedores(frmLotes parentForm) {
        initComponents();
        configurarListenerBusqueda();
        this.parentForm = parentForm;
        provDAO = new ProveedorDAO();
        this.model=(DefaultTableModel) this.jTable1.getModel();
        this.listaProveedores=new ArrayList();
        cargarTabla();
    }
    
    private void cargarTabla(){
        
        this.model.setRowCount(0);
        this.listaProveedores = this.provDAO.ConsultarProveedores();
        for (int i = 0; i < this.listaProveedores.size(); i++) {
            Proveedor prov=this.listaProveedores.get(i);
            String[] data= {Integer.toString(prov.getIdproveedor()), prov.getNombreProveedor()};
            this.model.addRow(data);
        }
    }
    private void configurarListenerBusqueda() {
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarFiltro();
            }

            // Método que actualiza el filtro al cambiar el texto
            private void actualizarFiltro() {
                // Obtener el texto de búsqueda
                String textoBusqueda = txtBuscar.getText(); // Asegúrate de que txtBuscar es el campo de texto donde el usuario ingresa el término de búsqueda

                // Llamar al método de filtrado
                filtrarTabla(textoBusqueda);
            }
        });
    }
    
        private void filtrarTabla(String textoBusqueda) {
        // Crear el RowFilter que busca coincidencias en la columna de nombres de medicamentos
        RowFilter<Object, Object> rf = RowFilter.regexFilter("(?i)" + textoBusqueda, 1); // 1 es el índice de la columna 'Nombre Medicamento'

        // Aplicar el filtro al modelo
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(this.model);
        sorter.setRowFilter(rf);
        this.jTable1.setRowSorter(sorter);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        pnlPrincipal.setBackground(new java.awt.Color(56, 102, 65));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PROVEEDOR"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscar)
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = this.jTable1.getSelectedRow();
        int id = Integer.parseInt(this.jTable1.getValueAt(fila, 0).toString());

        String nombre = (String) jTable1.getValueAt(fila, 1);

        parentForm.setProveedor(nombre, id);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
