/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Entidades.Lote;
import Entidades.Medicamento;
import Entidades.Usuario;
import com.toedter.calendar.JDateChooser;
import EntidadesDAO.LoteDAO;
import Vistas.frmAdministrador;
import Vistas.frmClienteSeleccionar;
import Vistas.frmMedicamentos;
import Vistas.frmUsuario;
import Vistas.frmVerMedicinas;
import Vistas.frmVerProveedores;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre
 */
public class frmLotes extends javax.swing.JPanel {
    
    private ArrayList<Lote> listaLotes;
    private DefaultTableModel tablaLotes;
    private LoteDAO loteDAO;
    private Lote lote;
    private Usuario userSesion;
    private SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-mm-dd");
    frmAdministrador parent;
    frmUsuario parentUsuario;
    boolean blnEditar;
    private Component rootPane;
    Medicamento medicinaSeleccionada;
    
    /**
     * Creates new form frmLotes
     */
    public frmLotes() {
        initComponents();
        listaLotes = new ArrayList<>();
        tablaLotes = (DefaultTableModel) this.jTable1.getModel();
        loteDAO = new LoteDAO();
        CargarTablaLotes();
        this.jDateChooser1.getDateEditor().setEnabled(false);
        this.blnEditar = false;
    }
        public frmLotes(Usuario userFrmPrincipal, frmAdministrador parent) {
        initComponents();
        this.parent = parent;
        this.medicinaSeleccionada = new Medicamento();
        this.userSesion = userFrmPrincipal;
        listaLotes = new ArrayList<>();
        tablaLotes = (DefaultTableModel) this.jTable1.getModel();
        loteDAO = new LoteDAO();
        CargarTablaLotes();
        this.jDateChooser1.getDateEditor().setEnabled(false);
        this.blnEditar = false;
    }

    public frmLotes(Usuario userFrmPrincipal, frmUsuario parent) {
        initComponents();
        this.medicinaSeleccionada = new Medicamento();
        this.parentUsuario = parent;
        this.userSesion = userFrmPrincipal;
        listaLotes = new ArrayList<>();
        tablaLotes = (DefaultTableModel) this.jTable1.getModel();
        loteDAO = new LoteDAO();
        CargarTablaLotes();
        this.jDateChooser1.getDateEditor().setEnabled(false);
        this.blnEditar = false;
    }

    public void setMedicina(Medicamento medicinaSeleccionada) {
        this.medicinaSeleccionada = medicinaSeleccionada;
        this.jTextField6.setText(this.medicinaSeleccionada.getNombre()); 
        this.jLabel11.setText(Integer.toString(this.medicinaSeleccionada.getIdMedicamento()));
    }
    
    public void setProveedor(String nombre, int id) {
        this.jTextField1.setText(nombre); 
        this.jLabel8.setText(Integer.toString(id));
    }
        
    private void CargarTablaLotes() {
        this.tablaLotes.setRowCount(0);
        this.listaLotes = this.loteDAO.ConsultarLote();
        
        for(int i=0; i<this.listaLotes.size(); i++)
        {
            try{
               String[] registroLotes={
                Integer.toString(this.listaLotes.get(i).getIdLote()),
                this.listaLotes.get(i).getNombreMedicamento(),
                Integer.toString(this.listaLotes.get(i).getCantidad()),
                Double.toString(this.listaLotes.get(i).getPrecioCosto()),
                Double.toString(this.listaLotes.get(i).getPrecioMayoreo()),
                Double.toString(this.listaLotes.get(i).getPrecioUnitario()),
                formatoFecha.format(this.listaLotes.get(i).getFecha()),
            };
            
            this.tablaLotes.addRow(registroLotes);
            }
            catch (Exception e)
            {
                e.printStackTrace(); // Mostrar el error en consola
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEditar = new javax.swing.JMenuItem();
        menuEliminar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        txtEmpleado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEditar);

        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);

        setBackground(new java.awt.Color(56, 102, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MEDICAMENTO", "CANTIDAD", "PROVEEDOR", "COSTO", "MAYOREO", "UNITARIO"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 640, 580));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 270, 30));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Límite stock");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 120, 30));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 120, -1));

        txtEmpleado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtEmpleado.setForeground(new java.awt.Color(204, 255, 204));
        add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 13, 270, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio unitario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 130, 30));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 110, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 120, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 270, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ubicación");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 120, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 270, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Costo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 120, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Lotes/btnComprarLote.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 270, 50));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha caducidad");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 200, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 140, 40));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 140, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio Mayoreo");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 130, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Lotes/btnOrdenar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Lotes/btnFiltrar.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 30, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 60, 30));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 140, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Medicamento/btnBuscar.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 40, 40));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 70, 30));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 270, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Medicamento/btnBuscar.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 40, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Producto");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 120, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Proveedor");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Lotes/FondoLabel.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!this.blnEditar){
            if(!this.jTextField1.getText().isBlank() && !this.jTextField1.getText().isEmpty() && !this.jTextField2.getText().isBlank() &&
                !this.jTextField2.getText().isEmpty() && !this.jTextField3.getText().isBlank() && !this.jTextField3.getText().isEmpty()
                && !this.jTextField4.getText().isBlank() && !this.jTextField4.getText().isEmpty() && !this.jTextField5.getText().isBlank()
                && !this.jTextField5.getText().isEmpty() && !this.jTextField6.getText().isBlank() && !this.jTextField6.getText().isEmpty()
                && (int)this.jSpinner1.getValue()!=0 && (int)this.jSpinner2.getValue()!=0){
            
                Lote lote = new Lote();
                lote.setIdMedicamento(Integer.parseInt(this.jLabel11.getText()));
                lote.setCantidad((int) jSpinner1.getValue());
                lote.setLimite((int) jSpinner2.getValue());
                lote.setIdProveedor(Integer.parseInt(this.jLabel8.getText()));
                lote.setIdUsuario(this.userSesion.getIdusuario());
                lote.setPrecioCosto(Double.parseDouble(this.jTextField2.getText()));
                lote.setPrecioUnitario(Double.parseDouble(this.jTextField5.getText()));
                lote.setPrecioMayoreo(Double.parseDouble(this.jTextField3.getText()));
                lote.setFecha(this.jDateChooser1.getDate());
                lote.setUbicacion(this.jTextField4.getText());

                this.loteDAO.InsertarLote(lote);
                JOptionPane.showMessageDialog(this, "Lote Agregado");
                this.CargarTablaLotes();

            }else{
                JOptionPane.showMessageDialog(this, "Ingrese información en los campos");
            }
        }else{
            Lote lote = new Lote();
                lote.setIdLote(lote.getIdLote());
                lote.setIdMedicamento(Integer.parseInt(this.jLabel11.getText()));
                lote.setCantidad((int) jSpinner1.getValue());
                lote.setLimite((int) jSpinner2.getValue());
                lote.setIdProveedor(Integer.parseInt(this.jLabel8.getText()));
                lote.setIdUsuario(this.userSesion.getIdusuario());
                lote.setPrecioCosto(Double.parseDouble(this.jTextField2.getText()));
                lote.setPrecioUnitario(Double.parseDouble(this.jTextField5.getText()));
                lote.setPrecioMayoreo(Double.parseDouble(this.jTextField3.getText()));
                lote.setFecha(this.jDateChooser1.getDate());
                lote.setUbicacion(this.jTextField4.getText());
                this.loteDAO.ActualizarLote(lote);
                JOptionPane.showMessageDialog(this, "Lote actualizado");
                this.CargarTablaLotes();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Comprobamos si 'parent' o 'parentUsuario' están disponibles
    if (this.parent != null) {
        // Si 'parent' no es null, utilizamos parent
        frmVerProveedores frm = new frmVerProveedores(this);
        frm.setVisible(true);
        this.parent.getDesktopPanel().add(frm);
        frm.moveToFront();
    } else if (this.parentUsuario != null) {
        // Si 'parentUsuario' no es null, utilizamos parentUsuario
        frmVerProveedores frm = new frmVerProveedores(this);
        frm.setVisible(true);
        this.parentUsuario.getDesktopPanel().add(frm);
        frm.moveToFront();
    } else {
        // Si ambos son null, mostramos un mensaje de error
        JOptionPane.showMessageDialog(null, "Error: No se puede acceder al panel principal.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // Comprobamos si 'parent' o 'parentUsuario' están disponibles
    if (this.parent != null) {
        // Si 'parent' no es null, utilizamos parent
        frmVerMedicinas frm = new frmVerMedicinas(this);
        frm.setVisible(true);
        this.parent.getDesktopPanel().add(frm);
        frm.moveToFront();
    } else if (this.parentUsuario != null) {
        // Si 'parentUsuario' no es null, utilizamos parentUsuario
        frmVerMedicinas frm = new frmVerMedicinas(this);
        frm.setVisible(true);
        this.parentUsuario.getDesktopPanel().add(frm);
        frm.moveToFront();
    } else {
        // Si ambos son null, mostramos un mensaje de error
        JOptionPane.showMessageDialog(null, "Error: No se puede acceder al panel principal.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        int fila = this.jTable1.getSelectedRow();
        if(fila != -1){
            this.blnEditar = true;
            lote = this.listaLotes.get(fila);
            this.jLabel11.setText(Integer.toString(lote.getIdMedicamento()));
            this.jTextField6.setText(lote.getNombreMedicamento());
            this.jLabel8.setText(Integer.toString(lote.getIdProveedor()));
            this.jTextField1.setText(lote.getNombreProveedor());
            this.jSpinner1.setValue(lote.getCantidad());
            this.jSpinner2.setValue(lote.getLimite());
            this.jTextField2.setText(Double.toString(lote.getPrecioCosto()));
            this.jTextField3.setText(Double.toString(lote.getPrecioMayoreo()));
            this.jTextField5.setText(Double.toString(lote.getPrecioUnitario()));
            this.jDateChooser1.setDate(lote.getFecha());
            this.jTextField4.setText(lote.getUbicacion());
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione una fila de la tabla", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        int fila = this.jTable1.getSelectedRow();
        lote = this.listaLotes.get(fila);
        if(fila != -1){
            int opc=JOptionPane.showConfirmDialog(rootPane,"Seguro que desea eliminar el lote?", "Advertencia!", JOptionPane.YES_NO_OPTION);
            if (opc==JOptionPane.OK_OPTION) {
                if (this.loteDAO.EliminarLote(this.lote.getIdMedicamento())) {
                    JOptionPane.showMessageDialog(rootPane, "", "Lote eliminado exitosamente!!", JOptionPane.INFORMATION_MESSAGE);
                    
                    this.CargarTablaLotes();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "El lote no pudo ser eliminado, intente nuevamente", "Error inesperado!!", JOptionPane.ERROR_MESSAGE);
                    this.CargarTablaLotes();
                }
            }
        }
    }//GEN-LAST:event_menuEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JLabel txtEmpleado;
    // End of variables declaration//GEN-END:variables
}
