/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Paneles;

import Entidades.Categoria;
import EntidadesDAO.CategoriaDAO;
import Vistas.frmMedicamentos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kater
 */
public class frmVerCategorias extends javax.swing.JInternalFrame {

    CategoriaDAO categoriaDAO;
    DefaultTableModel modelCategoria;
    ArrayList<Categoria> categorias;
    Categoria catSeleccionada;
    private frmMedicamentos parentForm;
    /**
     * Creates new form frmVerCategorias
     */
    public frmVerCategorias() {
        initComponents();
        this.categoriaDAO= new CategoriaDAO();
        this.modelCategoria=(DefaultTableModel) this.jTable1.getModel();
        this.categorias=new ArrayList();
        this.categorias=this.categoriaDAO.ConsultarCategorias();
        RecargarCategorias();
    }

     private void RecargarCategorias(){
        this.jTable1.clearSelection();
        this.modelCategoria.setRowCount(0);
        for (int i = 0; i < this.categorias.size(); i++) {
            Categoria cat=this.categorias.get(i);
            String[] data= {Integer.toString(cat.getIdcategoria()), cat.getNombreCategoria(), cat.getDescripcion()};
            this.modelCategoria.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        pnlPrincipal.setBackground(new java.awt.Color(56, 102, 65));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCIÓN"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = this.jTable1.getSelectedRow();
        int id = Integer.parseInt(this.jTable1.getValueAt(fila, 0).toString());
        
        String categoriaNombre = (String) jTable1.getValueAt(fila, 1);
        
        Categoria categoriaSeleccionada = this.categorias.get(fila);
        if (parentForm != null) {
            parentForm.setCategoria(categoriaSeleccionada); // Llama al método del formulario principal
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    // Método para establecer la referencia al formulario principal
    public void setParentForm(frmMedicamentos parentForm) {
        this.parentForm = parentForm;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
