/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Entidades.Usuario;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import Entidades.*;
import EntidadesDAO.*;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author andre
 */
public class pnlGraficos extends javax.swing.JPanel {

    private ArrayList<Venta> listaVentas;
    private VentaDAO ventaDAO;
    private Venta venta;
    /**
     * Creates new form pnlGraficos
     */
    Usuario userSesion;
    public pnlGraficos() {
        initComponents();
        listaVentas = new ArrayList<>();
        ventaDAO = new VentaDAO();
        venta = new Venta();
    }
    public pnlGraficos(Usuario userSesion) {
        initComponents();
        this.userSesion = userSesion;
        listaVentas = new ArrayList<>();
        ventaDAO = new VentaDAO();
        venta = new Venta();
    }
    
public void crearGrafico() {
    int j = 0;
    this.listaVentas = this.ventaDAO.ConsultarVentas();
    
    // Usamos un HashMap para almacenar las fechas (por mes)
    Map<String, Integer> conteoVentas = new HashMap<>();
    DefaultCategoryDataset datos = new DefaultCategoryDataset();
    
    // Llenamos el conteo de ventas por mes
    for (int i = 0; i < this.listaVentas.size(); i++) {
        String fechaMes = new SimpleDateFormat("yyyy-MM").format(this.listaVentas.get(i).getFechaVenta());
        // Obtener el IDVenta, pero realmente el IDVenta no se usa para el conteo de ventas aquí
        // Se usa la fecha y la cantidad de ventas por mes.
        conteoVentas.put(fechaMes, conteoVentas.getOrDefault(fechaMes, 0) + 1);
    }

    // Crear el conjunto de datos para el gráfico
    for (Map.Entry<String, Integer> entry : conteoVentas.entrySet()) {
        String fechaMes = entry.getKey();
        int totalVentas = entry.getValue();
        
        // Usamos la fecha como categoría en el eje X y la cantidad de ventas como valor Y
        //datos.addValue(totalVentas, "Ventas", fechaMes);  // "Ventas" es la serie, fechaMes es la categoría X
    }

    // Crear el gráfico de líneas usando DefaultCategoryDataset
    JFreeChart chart = ChartFactory.createLineChart(
        "Ventas por Mes",  // Título
        "Mes",  // Etiqueta eje X (mes)
        "Cantidad de Ventas",  // Etiqueta eje Y
        datos,  // Datos
        PlotOrientation.VERTICAL,
        true,  // Mostrar leyenda
        true,  // Mostrar tooltip
        false  // Mostrar URL
    );

    // Configurar el panel donde se dibujará el gráfico
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(jPanel1.getSize());
    jPanel1.removeAll();  // Limpiar el panel
    jPanel1.setLayout(new BorderLayout());
    jPanel1.add(chartPanel, BorderLayout.CENTER);  // Agregar el gráfico al panel
    jPanel1.revalidate();  // Redibujar el panel
    jPanel1.repaint();  // Redibujar la interfaz
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(56, 102, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
